### ISSUE TITLE
Sexagesimal positions

### ISSUE THREAD

**Issue by mwapst** [orppst/pst-gui#175]
Currently shown as degrees, which apparently some databases use instead of time. Do we need a conversion tool between hh:mm:ss and degrees, which will probably have rounding errors, so need to think about comparison with other databases. Which one will we store?
Also, maybe allow user to enter either, then calculate and present the other on the ui too.

**Comment by pahjbo** [comment]
this is related to the library mentioned in https://github.com/orppst/pst-gui/issues/72#issuecomment-1952247224

**Comment by Republicof1** [comment]
Just to provide a quick update on this task.

I have been working with a fork on TSOFA, the transpiled TS version of the SOFA C library. 
The key task was to make it a usable node package - which to a large extent it already was, albeit in a slightly awkward way. AstroLib is going be the much friendlier user layer package that allows us to convert to and from sexagesimal coordinates.

AstroLib is planned to be build on contemporary principles such as ECMA Script Modulse -ES Modules, or ESM for short. Working with TSOFA wasn't particularly harmonious as this was based on CommonJS. The documentation suggests that it is possible for these standards to interoperate, but in practice this is not ideal. As we contol the code for both TSOFA and AstroLib, it made reasonable sense to bring TSOFA up-to-date.

This work breaks into two tasks, 1. re-engineer TSOFA so that it is ESM compliant and (due it being built in TS) with build into JavaScript using TSC. 2. switch the testing fromework from TestyTS to the significantly better supported Jest.

I have now completed both of these tasks.

Remaining work on TSOFA: 
Port the changes from my fork of TSOFA into the principle repo.
Update the CI script in the principle repo to be able to run Jest tests.
Update the private npm package on prime repo (via publish action).

Next tasks for this issue:
Implement Jest in AstroLib, including making some tests that will pass as the solution develops.
Build out functions in AstroLib that can be accessed within Polaris
