### ISSUE TITLE
Create observation prompts user that a target is required first, but does not state a technical goal is also required.

### ISSUE THREAD

**Issue by AllanEngland** [orppst/pst-gui#57]
Adding an observation to a proposal that doesn't have any targets will prompt the user to add those first. 
However, it doesn't prompt them to add a technical goal beforehand which is also required to create an observation.

We could potentially add prompts to manage this (similar to targets), or allow a new observation without a defined technical goal.  Which then raises the question, do we continue to make users add targets before an observation too?

**Comment by alan-stokes** [comment]
there's a flip side to this, which I've been having some "fun" with this morning. which is once ya have a observation with a target or technical goal, you cant delete those technical goals / targets, because trying to do so will produce a failure in the request and result in it not being deleted. 

What I've been trying to do today was create a list of the "bound technical goals" inside the technical goal table page, so that we could disable the delete button on these technical goals. alas I'm hitting some hook issues where I call to many in different renders.

as the table inside assumes some of these are keys to other tables, i don't think you can leave them empty..... but its been a long while since I've played with primary / foreign keys and their relationships. So either we'd need to remove that relationship. or ensure a target exists beforehand.

**Comment by alan-stokes** [comment]
have found a way around the hooks issue in https://github.com/orppst/pst-gui/pull/67 by utilising a hook which extracts the entire proposal in 1 move. though it seems the data that is returned is not the correct data type. but oh well. it got the functionality to work.
