### ISSUE TITLE
SciencSpectralWindow type has an field named 'index', the purpose of which is unclear

### ISSUE THREAD

**Issue by DJWalker42** [orppst/pst-gui#63]
The 'index' field has a non-null constraint in the Postgres database so we have to give this field some value but its meaning is unclear.

**Comment by alan-stokes** [comment]
alas i didnt see this issue till now. so this comment has landed on a pr review as well. but putting here for completness as well.

if this is anything like the NGOT system. a spectral window had both a group index and an index for 2 reasons, 1. was to identify the baseband it was in (from 1 to 4) and a index which stated where it was within the baseband window. This was partly due to the windows being stored as 1 array, and so you had to traverse the entire array to locate all windows for a given baseband and the same for the position within the baseband. Maybe this is something simular?

**Comment by pahjbo** [comment]
As we cannot see the use for it, I have removed from the latest snapshot of the proposalDM
