### ISSUE TITLE
List of Targets shows reference system as "unknown" rather than ICRS or ICRF

### ISSUE THREAD

**Issue by DJWalker42** [orppst/pst-gui#98]

**Comment by pahjbo** [comment]
this might have occurred as a result of the latest reference handling.

**Comment by mwapst** [comment]
New Target offers J2000 as a coordinate system, which I don't think is quite right, and does not present a data entry field for the epoch itself.

The parent form correctly identifies the epoch as J2000, once selected in New Target, but displays 'unknown' for Reference System which presumably is for the coordinate system qualified with that epoch, had it been entered in New Target.

**Comment by pahjbo** [comment]
there is still a bit of confusion about epochs - see the discussion in #75  - so yes  there does need to be somewhere to add the epoch for the position - though if it is unknown, then it is probably better to leave it null, than put something wrong in.

**Comment by mwapst** [comment]
OK, but my point is that the New Target form offers a single selection for the Coordinate System data entry field, and that has the value 'J2000', which as we all know is not a coordinate system. The New Target form does offer data entry fields for RA & Dec, which implies equatorial coordinates, so the data entry field labelled Coordinate System has probably been mislabelled, and is almost certainly connected to the database table column 'Epoch' or whatever it is called. This thought is strengthened by the fact that the parent form showing the list of targets always has J2000 in its Epoch column.

I'm imagining that some investigators might declare their target positions in galactic coordinates, so the New Target form should probably allow for that too. And as there is a SolarSystemTarget entity in the model then possibly we need ecliptic coordinates too. So maybe New Target form should allow choice of supported coordinate systems, which would then drive the display of appropriate data entry fields, and prompt for a mandatory Epoch, defaulting to J2000, but allowing for what will presumably be called J2050 in the not too distant future. Earlier than J2000 would presumably be a vanishingly small edge case. The parent form listing the targets would need changing too, such that the coordinate symbols are shown within the row rather than as column headings.

**Comment by pahjbo** [comment]
OK this thread had got a bit confusing as it is about who different things - I have created a new issue #178 for the new target dialogue

**Comment by pahjbo** [comment]
Incidentally the root cause of this problem is still probably in the underlying generated code.

**Comment by pahjbo** [comment]
this should be fixed when the proposalDM v0.5 model is used

**Comment by DJWalker42** [comment]
This is now fixed, the reference system reads correctly in the targets table
